/**
 * Hand-authored skill / competency / role taxonomy for KaushalSetu.
 *
 * Terminology is aligned to India's frameworks: NSQF-style 1–8 proficiency,
 * NOS/QP-style role profiles (mandatory competencies + skills, preferred skills,
 * tools, behavioural competencies). Illustrative `nosCode`s reference the shape
 * of Sector Skill Council codes; they are not claimed to be official.
 *
 * Two role families are covered so the demo speaks to the Ministry of Ayush
 * context *and* the mainstream tech roles judges expect:
 *   • Ayurveda & life-sciences industry roles (formulation QA, regulatory,
 *     clinical research, pharmacovigilance, wellness program design)
 *   • Digital & data roles (ML, data analysis, full-stack, product analytics)
 */

import type {
  Competency,
  LearningResource,
  RoleProfile,
  Skill,
  SkillCategory,
} from "@/lib/domain/types";

export const skillCategories: SkillCategory[] = [
  { id: "cat-data", name: "Data & Analytics", cluster: "Digital & Data" },
  { id: "cat-ai", name: "AI & Machine Learning", cluster: "Digital & Data" },
  { id: "cat-swe", name: "Software Engineering", cluster: "Digital & Data" },
  { id: "cat-cloud", name: "Cloud & DevOps", cluster: "Digital & Data" },
  {
    id: "cat-ayur",
    name: "Ayurveda & Life Sciences",
    cluster: "Ayush & Life Sciences",
  },
  {
    id: "cat-qa",
    name: "Quality & Regulatory",
    cluster: "Ayush & Life Sciences",
  },
  {
    id: "cat-clin",
    name: "Clinical & Research",
    cluster: "Ayush & Life Sciences",
  },
  {
    id: "cat-well",
    name: "Wellness Operations",
    cluster: "Ayush & Life Sciences",
  },
  { id: "cat-biz", name: "Business & Communication", cluster: "Cross-cutting" },
];

/** id, name, category, prerequisites, nosCode?, description */
const S = (
  id: string,
  name: string,
  categoryId: string,
  prerequisiteIds: string[] = [],
  description = "",
  nosCode?: string,
): Skill => ({ id, name, categoryId, prerequisiteIds, description, nosCode });

export const skills: Skill[] = [
  // Data & Analytics
  S(
    "sk-sql",
    "SQL",
    "cat-data",
    [],
    "Relational querying, joins, window functions, query tuning.",
    "SSC/N/DATA/0210",
  ),
  S(
    "sk-excel",
    "Spreadsheet Modelling",
    "cat-data",
    [],
    "Advanced spreadsheet analysis, pivots, what-if modelling.",
  ),
  S(
    "sk-stats",
    "Applied Statistics",
    "cat-data",
    [],
    "Distributions, hypothesis testing, regression, sampling.",
  ),
  S(
    "sk-viz",
    "Data Visualisation",
    "cat-data",
    ["sk-excel"],
    "Charts that communicate; dashboard design; BI tools.",
  ),
  S(
    "sk-python-data",
    "Python for Data",
    "cat-data",
    [],
    "pandas, numpy, notebooks, data wrangling.",
    "SSC/N/DATA/0221",
  ),
  S(
    "sk-etl",
    "Data Pipelines / ETL",
    "cat-data",
    ["sk-python-data", "sk-sql"],
    "Ingestion, transformation, scheduling, data quality.",
  ),
  S(
    "sk-experiment",
    "Experiment Design & A/B",
    "cat-data",
    ["sk-stats"],
    "Designing and reading controlled experiments.",
  ),
  // AI / ML
  S(
    "sk-ml",
    "Machine Learning",
    "cat-ai",
    ["sk-python-data", "sk-stats"],
    "Supervised/unsupervised modelling, evaluation, tuning.",
    "SSC/N/AI/0301",
  ),
  S(
    "sk-dl",
    "Deep Learning",
    "cat-ai",
    ["sk-ml"],
    "Neural networks, CNN/RNN/transformers, training loops.",
  ),
  S(
    "sk-nlp",
    "Natural Language Processing",
    "cat-ai",
    ["sk-ml"],
    "Text processing, embeddings, transformers, evaluation.",
  ),
  S(
    "sk-mlops",
    "MLOps & Model Deployment",
    "cat-ai",
    ["sk-ml", "sk-docker"],
    "Serving, monitoring, retraining, model registries.",
  ),
  S(
    "sk-featureeng",
    "Feature Engineering",
    "cat-ai",
    ["sk-python-data"],
    "Constructing predictive features from raw data.",
  ),
  // Software Engineering
  S(
    "sk-js",
    "JavaScript / TypeScript",
    "cat-swe",
    [],
    "Modern JS/TS language and tooling.",
  ),
  S(
    "sk-react",
    "React / Next.js",
    "cat-swe",
    ["sk-js"],
    "Component architecture, SSR, app router patterns.",
  ),
  S(
    "sk-api",
    "API Design",
    "cat-swe",
    ["sk-js"],
    "REST/RPC design, versioning, contracts, docs.",
  ),
  S(
    "sk-db-design",
    "Database Design",
    "cat-swe",
    ["sk-sql"],
    "Normalisation, indexing, constraints, migrations.",
  ),
  S(
    "sk-testing",
    "Automated Testing",
    "cat-swe",
    ["sk-js"],
    "Unit, integration and E2E testing discipline.",
  ),
  S(
    "sk-git",
    "Version Control & Collaboration",
    "cat-swe",
    [],
    "Git workflows, code review, CI.",
  ),
  // Cloud / DevOps
  S(
    "sk-docker",
    "Containers (Docker)",
    "cat-cloud",
    ["sk-git"],
    "Images, registries, multi-stage builds.",
  ),
  S(
    "sk-cloud",
    "Cloud Fundamentals",
    "cat-cloud",
    [],
    "Compute, storage, networking, IAM on a major cloud.",
  ),
  S(
    "sk-cicd",
    "CI/CD",
    "cat-cloud",
    ["sk-git"],
    "Build/test/deploy automation pipelines.",
  ),
  // Ayurveda & Life Sciences
  S(
    "sk-ayur-pharma",
    "Ayurvedic Pharmaceutics (Rasashastra & Bhaishajya Kalpana)",
    "cat-ayur",
    [],
    "Classical formulation principles and preparation methods.",
    "SSC/N/AYU/1101",
  ),
  S(
    "sk-dravyaguna",
    "Dravyaguna (Materia Medica)",
    "cat-ayur",
    [],
    "Identification, properties and actions of medicinal plants.",
  ),
  S(
    "sk-ayur-diag",
    "Ayurvedic Clinical Assessment",
    "cat-clin",
    [],
    "Nadi, prakriti and roga-rogi pariksha; case documentation.",
  ),
  S(
    "sk-panchakarma",
    "Panchakarma Procedures",
    "cat-clin",
    ["sk-ayur-diag"],
    "Indications, protocols and safety of shodhana therapies.",
  ),
  S(
    "sk-herbal-id",
    "Botanical & Raw-Material Identification",
    "cat-qa",
    ["sk-dravyaguna"],
    "Macro/microscopic authentication of herbal raw materials.",
  ),
  S(
    "sk-gmp",
    "GMP & Quality Systems",
    "cat-qa",
    [],
    "Good Manufacturing Practice, SOPs, deviation handling.",
    "SSC/N/PHARMA/0402",
  ),
  S(
    "sk-qc-lab",
    "QC Laboratory Techniques",
    "cat-qa",
    ["sk-gmp"],
    "Assays, HPTLC/HPLC basics, stability, documentation.",
  ),
  S(
    "sk-reg-ayush",
    "AYUSH Regulatory Affairs",
    "cat-qa",
    ["sk-gmp"],
    "Drugs & Cosmetics Act Sch. T, licensing, label claims, ASU dossiers.",
  ),
  S(
    "sk-pv",
    "Pharmacovigilance",
    "cat-clin",
    [],
    "Adverse-event capture, causality, periodic safety reporting.",
  ),
  S(
    "sk-clin-research",
    "Clinical Research Methods",
    "cat-clin",
    ["sk-stats"],
    "Protocols, GCP, informed consent, trial operations.",
  ),
  S(
    "sk-lit-review",
    "Scientific Literature Review",
    "cat-clin",
    [],
    "Systematic search, appraisal and synthesis of evidence.",
  ),
  // Wellness Operations
  S(
    "sk-wellness-design",
    "Wellness Program Design",
    "cat-well",
    ["sk-ayur-diag"],
    "Protocol design for lifestyle, diet and therapy programs.",
  ),
  S(
    "sk-nutrition",
    "Ahara & Clinical Nutrition",
    "cat-well",
    [],
    "Ayurvedic dietetics and modern nutrition integration.",
  ),
  S(
    "sk-ops",
    "Operations & Scheduling",
    "cat-well",
    [],
    "Resource planning, SOP adherence, throughput.",
  ),
  S(
    "sk-cust-exp",
    "Client Experience & Counselling",
    "cat-well",
    [],
    "Consultation, adherence support, feedback loops.",
  ),
  // Business & Communication
  S(
    "sk-comm",
    "Professional Communication",
    "cat-biz",
    [],
    "Written and verbal clarity for a work context.",
  ),
  S(
    "sk-domain-writing",
    "Technical & Scientific Writing",
    "cat-biz",
    ["sk-comm"],
    "Reports, dossiers, documentation, content.",
  ),
  S(
    "sk-stakeholder",
    "Stakeholder Management",
    "cat-biz",
    ["sk-comm"],
    "Aligning multiple parties toward an outcome.",
  ),
  S(
    "sk-project-mgmt",
    "Project Management",
    "cat-biz",
    ["sk-stakeholder"],
    "Planning, tracking and delivering scoped work.",
  ),
  S(
    "sk-problem-solving",
    "Structured Problem Solving",
    "cat-biz",
    [],
    "Breaking ambiguous problems into tractable parts.",
  ),
  S(
    "sk-data-ethics",
    "Data Ethics & Privacy",
    "cat-biz",
    [],
    "Consent, minimisation, responsible use of data.",
  ),
  S(
    "sk-market-analysis",
    "Market & Competitive Analysis",
    "cat-biz",
    ["sk-problem-solving"],
    "Sizing, segmentation, positioning.",
  ),
];

export const skillById = new Map(skills.map((s) => [s.id, s]));

/** id, name, skillIds, nsqfBand, description, behavioural? */
const C = (
  id: string,
  name: string,
  skillIds: string[],
  nsqfBand: number,
  description: string,
  behavioural = false,
): Competency => ({
  id,
  name,
  skillIds,
  nsqfBand: nsqfBand as Competency["nsqfBand"],
  description,
  behavioural,
});

export const competencies: Competency[] = [
  C(
    "cmp-data-foundations",
    "Data Foundations",
    ["sk-sql", "sk-excel", "sk-python-data"],
    4,
    "Acquire, clean and query data reliably.",
  ),
  C(
    "cmp-analytical-thinking",
    "Analytical Thinking",
    ["sk-stats", "sk-problem-solving", "sk-experiment"],
    5,
    "Reason quantitatively about uncertain problems.",
  ),
  C(
    "cmp-ml-engineering",
    "ML Engineering",
    ["sk-ml", "sk-featureeng", "sk-dl", "sk-nlp"],
    6,
    "Build, evaluate and iterate on ML models.",
  ),
  C(
    "cmp-ml-delivery",
    "ML Delivery & Operations",
    ["sk-mlops", "sk-docker", "sk-cicd", "sk-api"],
    6,
    "Ship models to production and keep them healthy.",
  ),
  C(
    "cmp-insight-comm",
    "Insight Communication",
    ["sk-viz", "sk-comm", "sk-domain-writing"],
    4,
    "Turn analysis into decisions stakeholders act on.",
  ),
  C(
    "cmp-product-analytics",
    "Product Analytics",
    ["sk-experiment", "sk-sql", "sk-market-analysis", "sk-viz"],
    5,
    "Measure product behaviour and guide iteration.",
  ),
  C(
    "cmp-fullstack",
    "Full-Stack Web Engineering",
    ["sk-react", "sk-js", "sk-api", "sk-db-design", "sk-testing"],
    5,
    "Deliver end-to-end web features.",
  ),
  C(
    "cmp-eng-practice",
    "Engineering Practice",
    ["sk-git", "sk-testing", "sk-cicd"],
    4,
    "Work safely in a shared codebase.",
  ),
  C(
    "cmp-data-responsibility",
    "Responsible Data Practice",
    ["sk-data-ethics", "sk-lit-review"],
    4,
    "Handle data lawfully and ethically.",
    true,
  ),
  // Ayush & life sciences
  C(
    "cmp-ayur-formulation",
    "Ayurvedic Formulation Science",
    ["sk-ayur-pharma", "sk-dravyaguna", "sk-herbal-id"],
    5,
    "Understand and prepare classical & proprietary ASU formulations.",
  ),
  C(
    "cmp-quality-assurance",
    "Pharmaceutical Quality Assurance",
    ["sk-gmp", "sk-qc-lab", "sk-herbal-id"],
    6,
    "Assure identity, purity and consistency of ASU products.",
  ),
  C(
    "cmp-regulatory",
    "AYUSH Regulatory Competence",
    ["sk-reg-ayush", "sk-domain-writing", "sk-gmp"],
    6,
    "Navigate licensing, claims and dossiers for ASU drugs.",
  ),
  C(
    "cmp-clinical-research",
    "Clinical Research Competence",
    ["sk-clin-research", "sk-lit-review", "sk-stats", "sk-pv"],
    6,
    "Run evidence-generating studies to GCP.",
  ),
  C(
    "cmp-ayur-clinical",
    "Ayurvedic Clinical Practice",
    ["sk-ayur-diag", "sk-panchakarma", "sk-nutrition"],
    5,
    "Assess and manage patients per Ayurvedic principles.",
  ),
  C(
    "cmp-pharmacovigilance",
    "Pharmacovigilance",
    ["sk-pv", "sk-clin-research", "sk-domain-writing"],
    5,
    "Monitor and report product safety over the lifecycle.",
  ),
  C(
    "cmp-wellness-delivery",
    "Wellness Program Delivery",
    ["sk-wellness-design", "sk-nutrition", "sk-ops", "sk-cust-exp"],
    5,
    "Design and run structured wellness interventions.",
  ),
  // Cross-cutting
  C(
    "cmp-communication",
    "Professional Communication",
    ["sk-comm", "sk-domain-writing"],
    3,
    "Communicate clearly in a workplace.",
    true,
  ),
  C(
    "cmp-collaboration",
    "Collaboration & Ownership",
    ["sk-stakeholder", "sk-project-mgmt"],
    4,
    "Move shared work forward with others.",
    true,
  ),
  C(
    "cmp-domain-research",
    "Domain Research",
    ["sk-lit-review", "sk-market-analysis", "sk-problem-solving"],
    5,
    "Build a defensible view of an unfamiliar domain.",
  ),
];

export const competencyById = new Map(competencies.map((c) => [c.id, c]));

const req = (competencyId: string, mandatory: boolean, minLevel: number) => ({
  competencyId,
  mandatory,
  minLevel: minLevel as RoleProfile["requirements"][number]["minLevel"],
});

/** id, title, family, summary, requirements, mandatorySkillIds, preferredSkillIds, tools, behavioural, minEducation, minExperienceMonths, nsqfBand */
const R = (r: RoleProfile): RoleProfile => r;

export const roles: RoleProfile[] = [
  R({
    id: "role-ml-eng",
    title: "Machine Learning Engineer",
    family: "Data & AI",
    summary: "Builds, evaluates and ships ML models into production systems.",
    requirements: [
      req("cmp-ml-engineering", true, 5),
      req("cmp-data-foundations", true, 4),
      req("cmp-analytical-thinking", true, 4),
      req("cmp-ml-delivery", true, 4),
      req("cmp-eng-practice", false, 3),
      req("cmp-communication", false, 3),
    ],
    mandatorySkillIds: [
      "sk-ml",
      "sk-python-data",
      "sk-stats",
      "sk-featureeng",
      "sk-mlops",
    ],
    preferredSkillIds: ["sk-dl", "sk-nlp", "sk-docker", "sk-api", "sk-cloud"],
    tools: ["Python", "scikit-learn", "PyTorch", "Docker", "MLflow"],
    behavioural: ["Rigour", "Bias for evidence", "Communicates trade-offs"],
    minEducation: "B.Tech / B.E / MCA / M.Sc (any branch)",
    minExperienceMonths: 6,
    nsqfBand: 6,
  }),
  R({
    id: "role-data-analyst",
    title: "Data Analyst",
    family: "Data & AI",
    summary:
      "Answers business questions with data and communicates the decision.",
    requirements: [
      req("cmp-data-foundations", true, 4),
      req("cmp-analytical-thinking", true, 4),
      req("cmp-insight-comm", true, 4),
      req("cmp-data-responsibility", false, 3),
    ],
    mandatorySkillIds: ["sk-sql", "sk-stats", "sk-viz", "sk-excel"],
    preferredSkillIds: [
      "sk-python-data",
      "sk-experiment",
      "sk-market-analysis",
    ],
    tools: ["SQL", "Power BI / Metabase", "Spreadsheets", "Python (optional)"],
    behavioural: ["Curiosity", "Clarity", "Stakeholder empathy"],
    minEducation: "Any graduate degree",
    minExperienceMonths: 3,
    nsqfBand: 5,
  }),
  R({
    id: "role-data-scientist",
    title: "Data Scientist",
    family: "Data & AI",
    summary: "Frames problems, models them, and quantifies impact.",
    requirements: [
      req("cmp-ml-engineering", true, 5),
      req("cmp-analytical-thinking", true, 5),
      req("cmp-data-foundations", true, 4),
      req("cmp-insight-comm", true, 4),
      req("cmp-data-responsibility", false, 4),
    ],
    mandatorySkillIds: ["sk-ml", "sk-stats", "sk-python-data", "sk-experiment"],
    preferredSkillIds: ["sk-dl", "sk-nlp", "sk-viz", "sk-etl"],
    tools: ["Python", "Jupyter", "scikit-learn", "SQL"],
    behavioural: ["Scientific scepticism", "Storytelling"],
    minEducation: "B.Tech / M.Sc / MCA",
    minExperienceMonths: 6,
    nsqfBand: 6,
  }),
  R({
    id: "role-fullstack",
    title: "Full-Stack Developer",
    family: "Software Engineering",
    summary: "Delivers end-to-end product features across web and API.",
    requirements: [
      req("cmp-fullstack", true, 5),
      req("cmp-eng-practice", true, 4),
      req("cmp-collaboration", false, 3),
    ],
    mandatorySkillIds: [
      "sk-react",
      "sk-js",
      "sk-api",
      "sk-db-design",
      "sk-git",
    ],
    preferredSkillIds: ["sk-testing", "sk-docker", "sk-cicd", "sk-cloud"],
    tools: ["TypeScript", "React/Next.js", "PostgreSQL", "Git"],
    behavioural: ["Ownership", "Pragmatism"],
    minEducation: "B.Tech / BCA / MCA or equivalent portfolio",
    minExperienceMonths: 4,
    nsqfBand: 5,
  }),
  R({
    id: "role-product-analyst",
    title: "Product Analyst",
    family: "Data & AI",
    summary: "Instruments products, runs experiments, guides the roadmap.",
    requirements: [
      req("cmp-product-analytics", true, 4),
      req("cmp-analytical-thinking", true, 4),
      req("cmp-insight-comm", true, 4),
      req("cmp-collaboration", false, 3),
    ],
    mandatorySkillIds: [
      "sk-sql",
      "sk-experiment",
      "sk-viz",
      "sk-market-analysis",
    ],
    preferredSkillIds: ["sk-stats", "sk-python-data"],
    tools: ["SQL", "Amplitude / GA", "Spreadsheets"],
    behavioural: ["Product sense", "Decisiveness"],
    minEducation: "Any graduate degree",
    minExperienceMonths: 3,
    nsqfBand: 5,
  }),
  R({
    id: "role-formulation-qa",
    title: "Ayurvedic Formulation QA Analyst",
    family: "Regulatory & Quality",
    summary:
      "Assures identity, purity and batch consistency of ASU formulations.",
    requirements: [
      req("cmp-quality-assurance", true, 5),
      req("cmp-ayur-formulation", true, 4),
      req("cmp-communication", true, 3),
      req("cmp-collaboration", false, 3),
    ],
    mandatorySkillIds: [
      "sk-gmp",
      "sk-qc-lab",
      "sk-herbal-id",
      "sk-ayur-pharma",
    ],
    preferredSkillIds: ["sk-reg-ayush", "sk-domain-writing", "sk-dravyaguna"],
    tools: ["HPTLC", "HPLC", "Pharmacopoeial methods", "LIMS"],
    behavioural: ["Precision", "Documentation discipline", "Integrity"],
    minEducation: "BAMS / B.Pharm (Ayurveda) / B.Sc (Botany/Chemistry)",
    minExperienceMonths: 3,
    nsqfBand: 6,
  }),
  R({
    id: "role-reg-affairs",
    title: "AYUSH Regulatory Affairs Associate",
    family: "Regulatory & Quality",
    summary:
      "Prepares licensing dossiers and defends label claims for ASU drugs.",
    requirements: [
      req("cmp-regulatory", true, 5),
      req("cmp-ayur-formulation", true, 3),
      req("cmp-communication", true, 4),
      req("cmp-domain-research", false, 4),
    ],
    mandatorySkillIds: [
      "sk-reg-ayush",
      "sk-gmp",
      "sk-domain-writing",
      "sk-lit-review",
    ],
    preferredSkillIds: ["sk-qc-lab", "sk-pv", "sk-ayur-pharma"],
    tools: ["Sch. T / D&C Act", "AYUSH portal", "Pharmacopoeias"],
    behavioural: ["Thoroughness", "Regulatory judgement"],
    minEducation: "BAMS / B.Pharm / M.Pharm (Ayurveda)",
    minExperienceMonths: 6,
    nsqfBand: 6,
  }),
  R({
    id: "role-clin-research",
    title: "Clinical Research Associate (Ayurveda)",
    family: "Clinical & Research",
    summary:
      "Runs GCP-compliant studies generating evidence for Ayurvedic interventions.",
    requirements: [
      req("cmp-clinical-research", true, 5),
      req("cmp-ayur-clinical", true, 3),
      req("cmp-analytical-thinking", true, 4),
      req("cmp-communication", true, 4),
    ],
    mandatorySkillIds: [
      "sk-clin-research",
      "sk-lit-review",
      "sk-stats",
      "sk-ayur-diag",
    ],
    preferredSkillIds: ["sk-pv", "sk-domain-writing", "sk-data-ethics"],
    tools: ["GCP", "CTRI", "REDCap", "Statistical software"],
    behavioural: ["Ethical rigour", "Attention to protocol"],
    minEducation: "BAMS / MD (Ayurveda) / M.Sc Clinical Research",
    minExperienceMonths: 6,
    nsqfBand: 6,
  }),
  R({
    id: "role-pv-associate",
    title: "Pharmacovigilance Associate (ASU)",
    family: "Clinical & Research",
    summary: "Captures and assesses adverse events for ASU products.",
    requirements: [
      req("cmp-pharmacovigilance", true, 4),
      req("cmp-clinical-research", true, 3),
      req("cmp-communication", true, 4),
    ],
    mandatorySkillIds: ["sk-pv", "sk-clin-research", "sk-domain-writing"],
    preferredSkillIds: ["sk-lit-review", "sk-reg-ayush"],
    tools: ["PvPI forms", "Causality scales", "Safety databases"],
    behavioural: ["Vigilance", "Consistency"],
    minEducation: "BAMS / B.Pharm / Life-sciences graduate",
    minExperienceMonths: 3,
    nsqfBand: 5,
  }),
  R({
    id: "role-wellness-designer",
    title: "Ayurvedic Wellness Program Designer",
    family: "Wellness Operations",
    summary: "Designs and operationalises structured wellness interventions.",
    requirements: [
      req("cmp-wellness-delivery", true, 4),
      req("cmp-ayur-clinical", true, 3),
      req("cmp-collaboration", true, 4),
      req("cmp-insight-comm", false, 3),
    ],
    mandatorySkillIds: [
      "sk-wellness-design",
      "sk-nutrition",
      "sk-ayur-diag",
      "sk-ops",
    ],
    preferredSkillIds: ["sk-cust-exp", "sk-project-mgmt", "sk-viz"],
    tools: ["Protocol templates", "Scheduling systems", "Outcome trackers"],
    behavioural: ["Empathy", "Operational discipline"],
    minEducation: "BAMS / BNYS / Nutrition or allied graduate",
    minExperienceMonths: 3,
    nsqfBand: 5,
  }),
  R({
    id: "role-med-content",
    title: "Medical Content Specialist (Ayush)",
    family: "Business & Communication",
    summary:
      "Produces accurate, referenced scientific content for Ayush products.",
    requirements: [
      req("cmp-communication", true, 5),
      req("cmp-domain-research", true, 4),
      req("cmp-data-responsibility", false, 3),
    ],
    mandatorySkillIds: ["sk-domain-writing", "sk-lit-review", "sk-comm"],
    preferredSkillIds: ["sk-dravyaguna", "sk-reg-ayush", "sk-market-analysis"],
    tools: ["Reference managers", "Style guides", "CMS"],
    behavioural: ["Accuracy", "Editorial judgement"],
    minEducation: "BAMS / Life-sciences / Mass-comm graduate",
    minExperienceMonths: 0,
    nsqfBand: 5,
  }),
  R({
    id: "role-supplychain-analyst",
    title: "Herbal Supply-Chain Analyst",
    family: "Data & AI",
    summary:
      "Analyses sourcing, quality and cost across the herbal raw-material chain.",
    requirements: [
      req("cmp-data-foundations", true, 4),
      req("cmp-analytical-thinking", true, 4),
      req("cmp-insight-comm", true, 3),
      req("cmp-ayur-formulation", false, 3),
    ],
    mandatorySkillIds: ["sk-sql", "sk-excel", "sk-viz", "sk-herbal-id"],
    preferredSkillIds: ["sk-python-data", "sk-market-analysis", "sk-gmp"],
    tools: ["SQL", "Spreadsheets", "BI tools"],
    behavioural: ["Commercial awareness", "Detail orientation"],
    minEducation: "Any graduate degree",
    minExperienceMonths: 3,
    nsqfBand: 5,
  }),
];

export const roleById = new Map(roles.map((r) => [r.id, r]));

const LR = (
  id: string,
  title: string,
  provider: string,
  kind: LearningResource["kind"],
  skillIds: string[],
  hours: number,
  free: boolean,
): LearningResource => ({ id, title, provider, kind, skillIds, hours, free });

export const learningResources: LearningResource[] = [
  LR(
    "lr-nptel-ml",
    "Introduction to Machine Learning",
    "NPTEL / IIT Madras",
    "course",
    ["sk-ml", "sk-stats"],
    40,
    true,
  ),
  LR(
    "lr-dl-spec",
    "Deep Learning Foundations",
    "NPTEL",
    "course",
    ["sk-dl", "sk-ml"],
    48,
    true,
  ),
  LR(
    "lr-mlops-proj",
    "Deploy a model with Docker + FastAPI",
    "KaushalSetu Guided Project",
    "project",
    ["sk-mlops", "sk-docker", "sk-api"],
    20,
    true,
  ),
  LR(
    "lr-sql-track",
    "SQL for Analysts",
    "KaushalSetu Track",
    "course",
    ["sk-sql"],
    16,
    true,
  ),
  LR(
    "lr-stats-track",
    "Practical Statistics & Experiments",
    "KaushalSetu Track",
    "course",
    ["sk-stats", "sk-experiment"],
    24,
    true,
  ),
  LR(
    "lr-viz-proj",
    "Build a decision dashboard",
    "KaushalSetu Guided Project",
    "project",
    ["sk-viz", "sk-excel"],
    12,
    true,
  ),
  LR(
    "lr-react-track",
    "Modern React & Next.js",
    "KaushalSetu Track",
    "course",
    ["sk-react", "sk-js"],
    30,
    true,
  ),
  LR(
    "lr-api-proj",
    "Design and ship a REST API",
    "KaushalSetu Guided Project",
    "project",
    ["sk-api", "sk-db-design"],
    16,
    true,
  ),
  LR(
    "lr-testing",
    "Automated Testing Essentials",
    "KaushalSetu Track",
    "course",
    ["sk-testing", "sk-git"],
    10,
    true,
  ),
  LR(
    "lr-python-data",
    "Python for Data Analysis",
    "NPTEL",
    "course",
    ["sk-python-data"],
    30,
    true,
  ),
  LR(
    "lr-gmp",
    "GMP for AYUSH Manufacturing",
    "Pharmexcil / Industry",
    "course",
    ["sk-gmp"],
    20,
    false,
  ),
  LR(
    "lr-hptlc",
    "HPTLC & QC Lab Techniques",
    "Industry Lab Partner",
    "micro_credential",
    ["sk-qc-lab", "sk-herbal-id"],
    24,
    false,
  ),
  LR(
    "lr-reg-dossier",
    "Prepare an ASU licensing dossier",
    "KaushalSetu Guided Project",
    "project",
    ["sk-reg-ayush", "sk-domain-writing"],
    18,
    true,
  ),
  LR(
    "lr-gcp",
    "Good Clinical Practice (GCP)",
    "NIDM / ICMR-style",
    "micro_credential",
    ["sk-clin-research"],
    12,
    true,
  ),
  LR(
    "lr-pv",
    "Pharmacovigilance Fundamentals",
    "PvPI-style",
    "course",
    ["sk-pv"],
    10,
    true,
  ),
  LR(
    "lr-litreview",
    "Systematic Literature Review",
    "KaushalSetu Track",
    "course",
    ["sk-lit-review"],
    8,
    true,
  ),
  LR(
    "lr-dravya",
    "Dravyaguna & Raw-Material Identification",
    "AIIA-style",
    "course",
    ["sk-dravyaguna", "sk-herbal-id"],
    26,
    false,
  ),
  LR(
    "lr-panchakarma",
    "Panchakarma Protocols & Safety",
    "AIIA-style",
    "course",
    ["sk-panchakarma", "sk-ayur-diag"],
    30,
    false,
  ),
  LR(
    "lr-wellness-proj",
    "Design a 21-day wellness program",
    "KaushalSetu Guided Project",
    "project",
    ["sk-wellness-design", "sk-nutrition"],
    14,
    true,
  ),
  LR(
    "lr-writing",
    "Technical & Scientific Writing",
    "KaushalSetu Track",
    "course",
    ["sk-domain-writing", "sk-comm"],
    10,
    true,
  ),
  LR(
    "lr-nlp",
    "NLP with Transformers",
    "Hugging Face-style",
    "course",
    ["sk-nlp"],
    20,
    true,
  ),
  LR(
    "lr-docker",
    "Containers from Scratch",
    "KaushalSetu Track",
    "course",
    ["sk-docker"],
    8,
    true,
  ),
  LR(
    "lr-cloud",
    "Cloud Fundamentals",
    "Major Cloud (free tier)",
    "course",
    ["sk-cloud", "sk-cicd"],
    16,
    true,
  ),
  LR(
    "lr-mentor-ml",
    "1:1 Mentorship — ML career",
    "Industry Mentor Pool",
    "mentorship",
    ["sk-ml", "sk-mlops"],
    6,
    true,
  ),
  LR(
    "lr-mentor-reg",
    "1:1 Mentorship — AYUSH regulatory",
    "Industry Mentor Pool",
    "mentorship",
    ["sk-reg-ayush"],
    6,
    true,
  ),
];

export const learningById = new Map(learningResources.map((l) => [l.id, l]));
